export const list = [
  {
    id: 111,
    title: "Chrome 111",
    yearQuarter: "2023Q1",
    video: "",
  },
  {
    id: 110,
    title: "Chrome 110",
    yearQuarter: "2023Q1",
    video: "",
  },
  {
    id: 109,
    title: "Chrome 109",
    yearQuarter: "2023Q1",
    video: "PupwBARjaYU",
  },
  {
    id: 108,
    title: "Chrome 108",
    yearQuarter: "2022Q4",
    video: "UVtXrWvq_oI",
  },
  {
    id: 107,
    title: "Chrome 107",
    yearQuarter: "2022Q4",
    video: "1uwv6HbR8HU",
  },
  {
    id: 106,
    title: "Chrome 106",
    yearQuarter: "2022Q4",
    video: "5gBqTXctxO8",
  },
  {
    id: 105,
    title: "Chrome 105",
    yearQuarter: "2022Q3",
    video: "bHw_56RiVsg",
  },
  {
    id: 104,
    title: "Chrome 104",
    yearQuarter: "2022Q3",
    video: "4RXWfw7Xg_Y",
  },
  {
    id: 103,
    title: "Chrome 103",
    yearQuarter: "2022Q2",
    video: "LyMts4yfQu8",
  },
  {
    id: 102,
    title: "Chrome 102",
    yearQuarter: "2022Q2",
    video: "0V_ph7PA_aw",
  },
  {
    id: 101,
    title: "Chrome 101",
    yearQuarter: "2022Q2",
    video: "u9GRAliBrM8",
  },
  {
    id: 100,
    title: "Chrome 100",
    yearQuarter: "2022Q1",
    video: "DAD72grzDDc",
  },
  {
    id: 99,
    title: "Chrome 99",
    yearQuarter: "2022Q1",
    video: "zFVWeOKZBHs",
  },
  {
    id: 98,
    title: "Chrome 98",
    yearQuarter: "2022Q1",
    video: "YqkIS88VulM",
  },
  {
    id: 97,
    title: "Chrome 97",
    yearQuarter: "2021Q4",
    video: "cGotLGL1-Ko",
  },
  {
    id: 96,
    title: "Chrome 96",
    yearQuarter: "2021Q4",
    video: "3CXbhnaFNEw",
  },
  {
    id: 95,
    title: "Chrome 95",
    video: "T_Ppg7ghrWM",
  },
  {
    id: 94,
    title: "Chrome 94",
    video: "N9Jiou61WH4",
  },
  {
    id: 93,
    title: "Chrome 93",
    video: "1VaPAnUGRz8",
  },
  {
    id: 92,
    title: "Chrome 92",
    video: "2baY3JpCxpo",
  },
  {
    id: 91,
    title: "Chrome 91",
    video: "Givhtk3rObE",
  },
  {
    id: 90,
    title: "Chrome 90",
    video: "kOodTLAjPsE",
  },
  {
    id: 89,
    title: "Chrome 89",
    video: "VtaRYSBIbU4",
  },
  {
    id: 88,
    title: "Chrome 88",
    video: "3tUXV_n3yng",
  },
  {
    id: 87,
    title: "Chrome 87",
    video: "bE3O6EhLjPc",
  },
  {
    id: 86,
    title: "Chrome 86",
    video: "koUsK58dpNo",
  },
  {
    id: 85,
    title: "Chrome 85",
    video: "NOal2gTzftI",
  },
  {
    id: 84,
    title: "Chrome 84",
    video: "dgYAlcJonxo",
  },
  {
    id: 83,
    title: "Chrome 83",
    video: "MLNERCykDPg",
  },
  {
    id: 81,
    title: "Chrome 81",
    video: "HJNaNDspffM",
  },
  {
    id: 80,
    title: "Chrome 80",
    video: "2EiPb1opH3g",
  },
  {
    id: 79,
    title: "Chrome 79",
    video: "kobvF5cs6xY",
  },
  {
    id: 78,
    title: "Chrome 78",
    video: "VNkctDLYP6o",
  },
  {
    id: 77,
    title: "Chrome 77",
    video: "R8KzoMoKhnM",
  },
  {
    id: 76,
    title: "Chrome 76",
    video: "GLUB2yzk0ZQ",
  },
  {
    id: 75,
    title: "Chrome 75",
    video: "6zKPwOMFsa4",
  },
  {
    id: 74,
    title: "Chrome 74",
    video: "I14fXc7sXdU",
  },
  {
    id: 73,
    title: "Chrome 73",
    video: "uddZX9ZK6wY",
  },
  {
    id: 72,
    title: "Chrome 72",
    video: "XVJxlEdB230",
  },
  {
    id: 71,
    title: "Chrome 71",
    video: "fJxFZO8OEEs",
  },
  {
    id: 70,
    title: "Chrome 70",
    video: "LJq8vg8ktdQ",
  },
  {
    id: 68,
    title: "Chrome 68",
    video: "br4JZ5qz_20",
  },
  {
    id: 67,
    title: "Chrome 67",
    video: "4EdPq9Nw6uI",
  },
  {
    id: 66,
    title: "Chrome 66",
    video: "eaYXFTJVewA",
  },
  {
    id: 65,
    title: "Chrome 65",
    video: "D1pV7ermy6w",
  },
  {
    id: 64,
    title: "Chrome 64",
    video: "90wNAn05Cf4",
  },
  {
    id: 63,
    title: "Chrome 63",
    video: "Eyw_mwbABIQ",
  },
  {
    id: 62,
    title: "Chrome 62",
    video: "eD4fiqjaxHw",
  },
  {
    id: 61,
    title: "Chrome 61",
    video: "Lscb4SL58X4",
  },
  {
    id: 60,
    title: "Chrome 60",
    video: "Qnmb2YhkQmQ",
  },
  {
    id: 59,
    title: "Chrome 59",
    video: "4mx1m7UbBR0",
  },
];
